define(['jquery'],function(jquery){
    //第一种写法
    $.ajax({
        url:"../../js/json/collection.json",
        dataType:"json",
        type:"get",
        success:function(data){
            //注册一个Handlebars模版，通过id找到某一个模版，获取模版的html框架
            var myTemplate = Handlebars.compile($("#template_collection").html());
            //将json对象用刚刚注册的Handlebars模版封装，得到最终的html，插入到基础table中。
            $('#collection').html(myTemplate(data));
        }
    });
    /*所有店铺*/
    $('.store').click(function(){
        $(this).addClass('collnow');
        $(this).parent().siblings().children().removeClass('collnow');
        $('#collection').empty();
        $.ajax({
            url:"../../js/json/collection.json",
            dataType:"json",
            type:"get",
            success:function(data){               
                //注册一个Handlebars模版，通过id找到某一个模版，获取模版的html框架
                var myTemplate = Handlebars.compile($("#template_collection").html());
                //将json对象用刚刚注册的Handlebars模版封装，得到最终的html，插入到基础table中。
                $('#collection').html(myTemplate(data));
            }
        });
    });
    /*所有商品*/
    $('.commodity').click(function(){
        $(this).addClass('collnow');
        $(this).parent().siblings().children().removeClass('collnow');
        $('#collection').empty();
        $.ajax({
            url:"../../js/json/commodity.json",
            dataType:"json",
            type:"get",
            success:function(data){                
                //注册一个Handlebars模版，通过id找到某一个模版，获取模版的html框架
                var myTemplate = Handlebars.compile($("#template_collection").html());
                //将json对象用刚刚注册的Handlebars模版封装，得到最终的html，插入到基础table中。
                $('#collection').html(myTemplate(data));
            }
        });
    });
});